services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      CATALOG_SERVICE_URL: catalog:50051
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app

  catalog:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    environment:
      DATABASE_CONN_STRING: postgres://postgres:secret@postgres/postgres
      CATALOG_SERVICE_PORT: 50051
    volumes:
      - ./catalog-service:/app

  postgres:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080