services:

  catalog:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 8080:8080
    volumes:
      - ./catalog-service:/app

  postgres:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    ports:
      - 8081:8080